Project Structure
arcilli/browser-history pull request #12
Opened 2021-08-17 13:15 UTC by liza-i

2021-08-17 13:22 UTC, arcilli requested changes
We should also have the files hierarchy (e.g. src/main/scala/..)

Ideally, we would have also the server setup (eg. have a working route which will display `hello world`)

2021-08-18 06:35 UTC, arcilli requested changes
I think we're missing `project/build.properties` file also.

2021-08-18 07:25 UTC, dia28 approved these changes

2021-08-18 07:27 UTC, AntociGabriel approved these changes

2021-08-18 09:04 UTC, arcilli approved these changes

2021-08-18 10:31 UTC, merged